# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import nlu_service_pb2 as nlu__service__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in nlu_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class NLUServiceStub(object):
    """NLU Service for intent classification and parameter extraction
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Predict = channel.unary_unary(
                '/nlu.NLUService/Predict',
                request_serializer=nlu__service__pb2.PredictRequest.SerializeToString,
                response_deserializer=nlu__service__pb2.PredictResponse.FromString,
                _registered_method=True)
        self.PredictBatch = channel.unary_unary(
                '/nlu.NLUService/PredictBatch',
                request_serializer=nlu__service__pb2.PredictBatchRequest.SerializeToString,
                response_deserializer=nlu__service__pb2.PredictBatchResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/nlu.NLUService/HealthCheck',
                request_serializer=nlu__service__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=nlu__service__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class NLUServiceServicer(object):
    """NLU Service for intent classification and parameter extraction
    """

    def Predict(self, request, context):
        """Single prediction
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PredictBatch(self, request, context):
        """Batch predictions
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Health check
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NLUServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Predict': grpc.unary_unary_rpc_method_handler(
                    servicer.Predict,
                    request_deserializer=nlu__service__pb2.PredictRequest.FromString,
                    response_serializer=nlu__service__pb2.PredictResponse.SerializeToString,
            ),
            'PredictBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.PredictBatch,
                    request_deserializer=nlu__service__pb2.PredictBatchRequest.FromString,
                    response_serializer=nlu__service__pb2.PredictBatchResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=nlu__service__pb2.HealthCheckRequest.FromString,
                    response_serializer=nlu__service__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'nlu.NLUService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('nlu.NLUService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NLUService(object):
    """NLU Service for intent classification and parameter extraction
    """

    @staticmethod
    def Predict(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nlu.NLUService/Predict',
            nlu__service__pb2.PredictRequest.SerializeToString,
            nlu__service__pb2.PredictResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PredictBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nlu.NLUService/PredictBatch',
            nlu__service__pb2.PredictBatchRequest.SerializeToString,
            nlu__service__pb2.PredictBatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nlu.NLUService/HealthCheck',
            nlu__service__pb2.HealthCheckRequest.SerializeToString,
            nlu__service__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
