# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: nlu_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'nlu_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11nlu_service.proto\x12\x03nlu\"l\n\x0ePredictRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x17\n\nmax_length\x18\x02 \x01(\x05H\x00\x88\x01\x01\x12\x16\n\tnum_beams\x18\x03 \x01(\x05H\x01\x88\x01\x01\x42\r\n\x0b_max_lengthB\x0c\n\n_num_beams\"\xe3\x01\n\x0fPredictResponse\x12\x0e\n\x06intent\x18\x01 \x01(\t\x12\x30\n\x06params\x18\x02 \x03(\x0b\x32 .nlu.PredictResponse.ParamsEntry\x12\x17\n\nraw_output\x18\x03 \x01(\tH\x00\x88\x01\x01\x12\x12\n\x05\x65rror\x18\x04 \x01(\tH\x01\x88\x01\x01\x12\x19\n\x11inference_time_ms\x18\x05 \x01(\x02\x1a-\n\x0bParamsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x42\r\n\x0b_raw_outputB\x08\n\x06_error\"r\n\x13PredictBatchRequest\x12\r\n\x05texts\x18\x01 \x03(\t\x12\x17\n\nmax_length\x18\x02 \x01(\x05H\x00\x88\x01\x01\x12\x16\n\tnum_beams\x18\x03 \x01(\x05H\x01\x88\x01\x01\x42\r\n\x0b_max_lengthB\x0c\n\n_num_beams\"b\n\x14PredictBatchResponse\x12)\n\x0bpredictions\x18\x01 \x03(\x0b\x32\x14.nlu.PredictResponse\x12\x1f\n\x17total_inference_time_ms\x18\x02 \x01(\x02\"\x14\n\x12HealthCheckRequest\"g\n\x13HealthCheckResponse\x12\x12\n\nis_healthy\x18\x01 \x01(\x08\x12\x12\n\nmodel_name\x18\x02 \x01(\t\x12\x0e\n\x06\x64\x65vice\x18\x03 \x01(\t\x12\x18\n\x10model_parameters\x18\x04 \x01(\x03\x32\xcf\x01\n\nNLUService\x12\x36\n\x07Predict\x12\x13.nlu.PredictRequest\x1a\x14.nlu.PredictResponse\"\x00\x12\x45\n\x0cPredictBatch\x12\x18.nlu.PredictBatchRequest\x1a\x19.nlu.PredictBatchResponse\"\x00\x12\x42\n\x0bHealthCheck\x12\x17.nlu.HealthCheckRequest\x1a\x18.nlu.HealthCheckResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'nlu_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PREDICTRESPONSE_PARAMSENTRY']._loaded_options = None
  _globals['_PREDICTRESPONSE_PARAMSENTRY']._serialized_options = b'8\001'
  _globals['_PREDICTREQUEST']._serialized_start=26
  _globals['_PREDICTREQUEST']._serialized_end=134
  _globals['_PREDICTRESPONSE']._serialized_start=137
  _globals['_PREDICTRESPONSE']._serialized_end=364
  _globals['_PREDICTRESPONSE_PARAMSENTRY']._serialized_start=294
  _globals['_PREDICTRESPONSE_PARAMSENTRY']._serialized_end=339
  _globals['_PREDICTBATCHREQUEST']._serialized_start=366
  _globals['_PREDICTBATCHREQUEST']._serialized_end=480
  _globals['_PREDICTBATCHRESPONSE']._serialized_start=482
  _globals['_PREDICTBATCHRESPONSE']._serialized_end=580
  _globals['_HEALTHCHECKREQUEST']._serialized_start=582
  _globals['_HEALTHCHECKREQUEST']._serialized_end=602
  _globals['_HEALTHCHECKRESPONSE']._serialized_start=604
  _globals['_HEALTHCHECKRESPONSE']._serialized_end=707
  _globals['_NLUSERVICE']._serialized_start=710
  _globals['_NLUSERVICE']._serialized_end=917
# @@protoc_insertion_point(module_scope)
